//  reviews
//

const inventory = [
  {
    id: 1,
    name: "Pomegranate (Anaar)",
    unit: "1 kg",
    price: 155,
    category: "fruits",
    image: "../images/p1.jpg",
    rating: 4,
    discount: 5,
  },
  {
    id: 2,
    name: "Apple (Washington)",
    unit: "500 gm",
    price: 130,
    category: "fruits",
    image: "../images/p2.jpg",
    rating: 5,
    discount: 2,
  },
  {
    id: 3,
    name: "Pineapple (Raja)",
    unit: "1 unit",
    price: 90,
    category: "fruits",
    image: "../images/p3.jpg",
    rating: 2,
    discount: 2,
  },
  {
    id: 4,
    name: "Kiwi",
    unit: "3 unit",
    price: 100,
    category: "fruits",
    image: "../images/p4.jpg",
    rating: 4,
    discount: 20,
  },
  {
    id: 5,
    name: "Pineapple (Rani)",
    unit: "1 unit",
    price: 80,
    category: "fruits",
    image: "../images/p5.jpg",
    rating: 5,
    discount: 5,
  },
  {
    id: 6,
    name: "Guava",
    unit: "6 unit",
    price: 100,
    category: "fruits",
    image: "../images/p6.jpg",
    rating: 5,
    discount: 5,
  },
  {
    id: 9,
    name: "Onion",
    unit: "1 kg",
    price: 30,
    category: "vegetables",
    image: "../images/p9.jpg",
    rating: 2,
    discount: 40,
  },
  {
    id: 10,
    name: "Large Round Brinjal ",
    unit: "500 gm",
    price: 20,
    category: "vegetables",
    image: "../images/p10.jpg",
    rating: 4,
    discount: 20,
  },
  {
    id: 11,
    name: "Tomato",
    unit: "1 kg",
    price: 50,
    category: "vegetables",
    image: "../images/p11.jpg",
    rating: 3,
    discount: 15,
  },
  {
    id: 12,
    name: "Potato Old",
    unit: "1 kg",
    price: 20,
    category: "vegetables",
    image: "../images/p12.jpg",
    rating: 4,
    discount: 10,
  },
  {
    id: 13,
    name: "Eggs",
    unit: "12 units",
    price: 85,
    category: "non-veg",
    image: "../images/p13.jpg",
    rating: 5,
    discount: 5,
  },
];

export const users = [
  {
    id: 1,
    email: "user1@m.com",
    password: "pass",
  },
  {
    id: 2,
    email: "user2@m.com",
    password: "pass",
  },
];

export default inventory;
